// <auto-generated />
using System;
using Assignment2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment2.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment2.Entities.Frontend", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("pass_word");

                    b.HasKey("UserName");

                    b.ToTable("frontend");
                });

            modelBuilder.Entity("Assignment2.Entities.Kitchen", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("pass_word");

                    b.HasKey("UserName");

                    b.ToTable("kitchen");
                });

            modelBuilder.Entity("Assignment2.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1011L);

                    b.Property<string>("AptSuite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apt_suite");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("date")
                        .HasColumnName("arrival_time");

                    b.Property<string>("BirthDay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("birth_day");

                    b.Property<int>("Breakfast")
                        .HasColumnType("int")
                        .HasColumnName("break_fast");

                    b.Property<string>("CardCvc")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .HasColumnName("card_cvc");

                    b.Property<string>("CardExp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("card_exp");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("card_number");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .HasColumnName("card_type");

                    b.Property<bool>("CheckIn")
                        .HasColumnType("bit")
                        .HasColumnName("check_in");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<bool>("Cleaning")
                        .HasColumnType("bit")
                        .HasColumnName("cleaning");

                    b.Property<int>("Dinner")
                        .HasColumnType("int")
                        .HasColumnName("dinner");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<int>("FoodBill")
                        .HasColumnType("int")
                        .HasColumnName("food_bill");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("LeavingTime")
                        .HasColumnType("date")
                        .HasColumnName("leaving_time");

                    b.Property<int>("Lunch")
                        .HasColumnType("int")
                        .HasColumnName("lunch");

                    b.Property<int>("NumberGuest")
                        .HasColumnType("int")
                        .HasColumnName("number_guest");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .HasColumnName("payment_type");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RoomFloor")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .HasColumnName("room_floor");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .HasColumnName("room_number");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .HasColumnName("room_type");

                    b.Property<bool>("SSurprise")
                        .HasColumnType("bit")
                        .HasColumnName("s_surprise");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("state");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street_address");

                    b.Property<bool>("SupplyStatus")
                        .HasColumnType("bit")
                        .HasColumnName("supply_status");

                    b.Property<double>("TotalBill")
                        .HasColumnType("float")
                        .HasColumnName("total_bill");

                    b.Property<bool>("Towel")
                        .HasColumnType("bit")
                        .HasColumnName("towel");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nchar(10)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.ToTable("reservation");
                });
#pragma warning restore 612, 618
        }
    }
}
