// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANnsX8i52pOXTIXQ1P9BYULWsBB8QOm2s',
    appId: '1:185880158083:web:e5debf088ce5cf08ef20b6',
    messagingSenderId: '185880158083',
    projectId: 'tech-company-portal',
    authDomain: 'tech-company-portal.firebaseapp.com',
    storageBucket: 'tech-company-portal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-jk36GsynuWlY0j4DMUzJx91JV4g-Xm0',
    appId: '1:185880158083:android:39a9cf0a8978c91aef20b6',
    messagingSenderId: '185880158083',
    projectId: 'tech-company-portal',
    storageBucket: 'tech-company-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0IwWY93CtR6CY2rh0dcV9akU9IJWuZfU',
    appId: '1:185880158083:ios:d4dab19a511c67a8ef20b6',
    messagingSenderId: '185880158083',
    projectId: 'tech-company-portal',
    storageBucket: 'tech-company-portal.firebasestorage.app',
    iosBundleId: 'com.example.assignmentD05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0IwWY93CtR6CY2rh0dcV9akU9IJWuZfU',
    appId: '1:185880158083:ios:d4dab19a511c67a8ef20b6',
    messagingSenderId: '185880158083',
    projectId: 'tech-company-portal',
    storageBucket: 'tech-company-portal.firebasestorage.app',
    iosBundleId: 'com.example.assignmentD05',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANnsX8i52pOXTIXQ1P9BYULWsBB8QOm2s',
    appId: '1:185880158083:web:bff97c2a81ba97ffef20b6',
    messagingSenderId: '185880158083',
    projectId: 'tech-company-portal',
    authDomain: 'tech-company-portal.firebaseapp.com',
    storageBucket: 'tech-company-portal.firebasestorage.app',
  );
}
